#!/bin/bash

/opt/gitlab-6.3.0-0/gitlab_management/sync_github/sync_bat &>>(/usr/local/bin/php -n -f /opt/gitlab-6.3.0-0/gitlab_management/phpmailer/sendmail.php "GitLab Sync GitHub44" >> /opt/gitlab-6.3.0-0/gitlab_management/phpmailer/sendmail.log);
